blackchoey/azure-cli-extensions

src/apic-extension/README.md
src/apic-extension/azext_apic_extension/_help.py
src/apic-extension/azext_apic_extension/custom.py

1. support yaml file in register command
2. fix `invalid api id` and `summary too long` error when register the pet store spec

feat: support yaml file in register command

---

.github/workflows/CD.yml
.github/workflows/CI.yml
.github/workflows/update_version.py

CI pipeline:
1. run `azdev style`, `azdev linter`, `azdev test` for pull requests and commits
CD pipeline:
1. Build and upload extension to GitHub releases after PR is merged
2. Support manually trigger the pipeline to generate a daily build

build: add cicd pipeline

---

.github/CODEOWNERS

Update codeowner for apic-extension, which is expected to be persisted in upstream repo.

chore: update codeowner for apic-extension

---

src/apic-extension/azext_apic_extension/azext_metadata.json

Revert min cli version change as previous PRs do not use features from newer CLI version. The version is changed because I use latest aaz-dev tool, which hardcoded the min CLI version to 2.57.
Will schedule discussions on our policy of min CLI version update based on inputs from Azure CLI team.

feat: revert min cli version change

---

src/apic-extension/azext_apic_extension/aaz/latest/apic/api/_create.py
src/apic-extension/azext_apic_extension/aaz/latest/apic/api/_update.py
src/apic-extension/azext_apic_extension/azext_metadata.json

1. Remove --terms-of-service parameter as it's not exposed in Azure Portal
2. Bump min Azure CLI version to 2.57. The change comes from latest aaz-dev. And APIC CLI will follow aaz-dev's configuration per discussion.
https://msazure.visualstudio.com/One/_workitems/edit/27531431

feat: remove --terms-of-service parameter

---

src/apic-extension/HISTORY.rst

update change per feedback comments in #18

doc: update changelog per feedback

---

.github/workflows/CI.yml

Run CI on multiple python version to detect code that is incompatible with different Python version.
Remove pull request event to avoid duplicate runs.

build: Run CI on multiple python version

---

src/apic-extension/azext_apic_extension/commands.py
src/apic-extension/azext_apic_extension/custom.py
src/apic-extension/azext_apic_extension/tests/latest/test_definition_commands.py

Remove `--file-name` parameter for `az apic api definition import-specification`, `az apic metadata create` and `az apic metadata update` command.
Users should use `@filename` syntax provided by Azure CLI to read parameter value from a file directly.
https://msazure.visualstudio.com/One/_workitems/edit/28069265

feat!: remove file name param

---

src/apic-extension/azext_apic_extension/aaz/latest/apic/api/deployment/_create.py
src/apic-extension/azext_apic_extension/aaz/latest/apic/api/deployment/_update.py
src/apic-extension/azext_apic_extension/tests/latest/test_deployment_commands.py

Remove `--state` parameter for `az apic api deployment` commands because there's no user scenario for it.
https://msazure.visualstudio.com/One/_workitems/edit/28106452

feat!: remove state param for deployment commands

---

src/apic-extension/azext_apic_extension/custom.py
src/apic-extension/azext_apic_extension/tests/latest/recordings/test_register_with_json_spec.yaml
src/apic-extension/azext_apic_extension/tests/latest/recordings/test_register_with_yml_spec.yaml
src/apic-extension/azext_apic_extension/tests/latest/test_register_command.py

The API title of APIs created by `az apic api register` command is not the same with provided spec. Fix this issue.
https://msazure.visualstudio.com/One/_queries/edit/27998100/?triage=true

fix: API title created by register command is not same with provided spec

---

src/apic-extension/HISTORY.rst
src/apic-extension/azext_apic_extension/azext_metadata.json
src/apic-extension/setup.py

1. Bump version to 1.0.0
2. Add changelog for 1.0.0. Will add more to the changelog with future P0 bug fix PRs.

build: bump version to 1.0.0 and add changelog

---

src/apic-extension/HISTORY.rst
src/apic-extension/azext_apic_extension/command_patches.py

* `--definition-id`, `--environment-id`, `--server`, `--title` parameters should be required in `az apic api deployment create` command
* `--format`, `--specification`, `--value` parameters should be required in `az apic api definition import-specification` command
https://msazure.visualstudio.com/One/_workitems/edit/28011693
https://msazure.visualstudio.com/One/_workitems/edit/28042590

fix: some parameters should be required in import-specification and deployment command

---

src/apic-extension/HISTORY.rst

Reviewed and updated 1.0.0 changelog (HIRSOTRY.rst) file

docs: update changelog for 1.0.0

---

src/apic-extension/azext_apic_extension/aaz/latest/apic/_create.py
src/apic-extension/azext_apic_extension/aaz/latest/apic/_list.py
src/apic-extension/azext_apic_extension/aaz/latest/apic/_show.py
src/apic-extension/azext_apic_extension/aaz/latest/apic/_update.py
src/apic-extension/azext_apic_extension/command_patches.py
src/apic-extension/azext_apic_extension/tests/latest/recordings/test_create_service_multiple_times.yaml
src/apic-extension/azext_apic_extension/tests/latest/recordings/test_examples_update_service_details.yaml
src/apic-extension/azext_apic_extension/tests/latest/recordings/test_update_service.yaml
src/apic-extension/azext_apic_extension/tests/latest/recordings/test_update_service_with_all_optional_params.yaml
src/apic-extension/azext_apic_extension/tests/latest/test_service_commands.py

1. Fix error when run create command against existing resource. Run create command against existing resource is usually used in CICD scenario.
2.  Change `az apic update` command back to PUT request as we have SKU support in http client now
The SKU parameter is hided temporary because there're too many SKU properties, we need further discussion on how SKU should be supported in CLI.
https://msazure.visualstudio.com/One/_workitems/edit/28011732
https://msazure.visualstudio.com/One/_workitems/edit/27863921

fix: cannot run create command against existing resource

---

src/apic-extension/azext_apic_extension/aaz/latest/apic/api/_update.py
src/apic-extension/azext_apic_extension/custom.py
src/apic-extension/azext_apic_extension/tests/latest/recordings/test_examples_update_single_custom_metadata.yaml
src/apic-extension/azext_apic_extension/tests/latest/test_api_commands.py

refactor: add apic api update example

---

src/apic-extension/HISTORY.rst

doc: update 1.0.1 release history

---

src/apic-extension/HISTORY.rst

Update V1.1.0 history

---

src/apic-extension/azext_apic_extension/aaz/latest/apic/api/_create.py
src/apic-extension/azext_apic_extension/aaz/latest/apic/api/_update.py
src/apic-extension/azext_apic_extension/aaz/latest/apic/api/definition/_import_specification.py
src/apic-extension/azext_apic_extension/aaz/latest/apic/api/deployment/_create.py
src/apic-extension/azext_apic_extension/aaz/latest/apic/metadata/_create.py
src/apic-extension/azext_apic_extension/aaz/latest/apic/metadata/_update.py

refactor: add @filename.json examples

---

src/apic-extension/azext_apic_extension/aaz/latest/apic/integration/_create.py
src/apic-extension/azext_apic_extension/aaz/latest/apic/integration/_delete.py
src/apic-extension/azext_apic_extension/aaz/latest/apic/integration/_show.py
src/apic-extension/azext_apic_extension/command_patches.py

1. Use the `--integration-name/-i` parameter instead of `--integration-id` in the `create`, `delete`, and `show` commands to specify the name of the integration.
2. Use abbreviations in command name: `az apic integration create apim` and `az apic integration create aws`
3. Follow CLI's recommendation to use `--azure-apim` to replace `--apim-name`, `--apim-resource-group` and `--apim-subscription-id`. The new parameter accepts an APIM name or APIM resource id. When APIM name is provided, CLI will assume the APIM is in the same resource group as APIC.

feat: rename command and param names

---

.github/workflows/CI.yml
src/apic-extension/azext_apic_extension/tests/latest/constants.py
src/apic-extension/azext_apic_extension/tests/latest/recordings/test_integration_create_aws.yaml
src/apic-extension/azext_apic_extension/tests/latest/test_integration_commands.py
src/apic-extension/azext_apic_extension/tests/latest/utils.py

test: add aws sync testcase

---

src/apic-extension/azext_apic_extension/aaz/latest/apic/_update.py
src/apic-extension/azext_apic_extension/command_patches.py

refactor: integration examples and bad example for `apic update`
